name: AddData

on:
 schedule:
    # * is a special character in YAML so you have to quote this string
    # - cron:  '5 2 * * *'
    - cron:  '5 2 * * *'
      
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: generate all
      run: |
        echo 'start generate'        
        chmod +x ./makeData/addNew.bat
        cd makeData        
        ./addNew.bat
        cp ../obj/allData.js ../WFHResourcesApp/src/assets/
        echo 'finish generate all'

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add --all
        git commit -m "adding new data" -a --allow-empty
          
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
