
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: generating necessary folders
      run: |
          mkdir output
          
    - name: generate all
      run: |        
        chmod +x ./makeData/compile.bat
        cd makeData        
        rm -rf ./WFHAng
        ./compile.bat
        rm ../obj/all.md
        mv ./all.md ../obj/all.md
        echo "copy js"
        mv ./all.js ../obj/all.js
        echo "copied js"
        ls -l ../obj/all.*
        chmod 777 ../obj/all.md
        ls -l ../obj/all.*
        ls -lh ../docs/*
        rm ../docs/*.js
        rm ../docs/*.txt
        rm ../docs/*.css
        rm ../docs/*.html
        ls -lh ../docs/*
        ls -lh WFHAng/*
        cp WFHAng/* ../docs/ 
        #cp data.ts WFHResourcesApp/src/app/table-wfh/data.ts
        cp data.ts ../docs/data.ts 
        cp ../docs/index.html ../docs/404.html  
        ls -lh ../docs/*
        echo 'finish generate all'

    - name: generate html
      uses: docker://pandoc/latex:2.9
      with: ## needs a README in your repo root!          
        args: "-d makeData/headerIncludes.md"
      
    - name: modifying final files
      run: |
        ls -lh ./docs/*
        find . -name \*output.html
        cp ./output/output.html ./docs/output.html        
        rm -rf ./output
        ls -lh ./docs/*
    
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add --all
        git commit -m "generate html" -a --allow-empty
          
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
