
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
          echo generate help file
          mkdir output
          git pull
    - name: generate all
      run: |
        chmod +x ./makeData/compile.bat
        cd makeData        
        ./compile.bat
        mv ./all.md ../obj/all.md

    - name: generate html
      uses: docker://pandoc/latex:2.9
      with: ## needs a README in your repo root!          
        args: "README.md  obj/all.md --standalone -f gfm -t html  --toc -o output/output.html --metadata title=WorkFromHome_Resources"
      
    - run: |
        cp ./output/output.html ./docs/index.html        
        rm -rf ./output
    
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "generate html" -a --allow-empty
          
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
